alter TABLE GS_CDC.FT_STG_TRNS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ABMR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACCL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACCR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACCT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACGP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACGR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACGU move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACTA move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ACTP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ADTP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AICL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AISR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AOID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AOPT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AOST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AUGP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AUGR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AUOR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AURP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_AUSR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BALH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BDCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BDST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BHST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNCL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNCM move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNPS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNPT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNTY move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNVC move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_BNVL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_CACR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_CCRF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_CUST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_DSID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_DSRC move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_DWDS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_EADR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_EDMV move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_EIAT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_EIST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ENCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ENTR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ERVL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ETAM move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ETCL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ETCM move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ETID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ETMG move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_EXST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_EXTR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FECH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FFRL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FICL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FIDE move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FIGU move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FIID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FINR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FINS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FIRT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FLDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FNCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FNSR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FPGU move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FPRO move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FPTR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FRAP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_FRIP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_GCCM move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_GUID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_GUNT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_IDMV move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_IEDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_IEVP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_INCL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_INCS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_IPDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_IPST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_IRTY move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISAN move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISAS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISCD move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISCL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISCM move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISDE move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISGP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISGR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISGU move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISLL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISMC move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISPC move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISRT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISSU move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISTA move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_ISTY move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_LMCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_LMST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_MADR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_MIXR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_MKID move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_MKIS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_MRKT move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_MUST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_OPCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_OVRC move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_PEDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_PEVP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_POS1 move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_POS2 move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_PPDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RGCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RIDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RISS move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RIXR move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RTG1 move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RTNG move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_RTVL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_SEC1 move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_SRLE move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_SRPP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_STDF move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_SWCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_TRCP move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_TTCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_TTRL move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_UWCH move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_T_UWST move  tablespace LINDEX_TS ;
alter TABLE GS_CDC.FT_WF_UIWA move  tablespace LINDEX_TS ;
alter TABLE GS_GC.DEPLOYMENTSTORE move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_CFG_PUB1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_CFG_VRT1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_D_DMID move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_EV_EVIS move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_LOG_LGPD move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_LOG_LOGE move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_LOG_LOGF move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_LOG_LOGM move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_AUD1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_COMC move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_EQP1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_FIP1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_ISID_20180417 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_ISPC move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_MIXR_20180417 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_MKIS_20180417 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_MSGF move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_MSGP move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_MSGS move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_MSGV move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_PBC1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_POS1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_POS2 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_RTG1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_SEC1 move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_TKTN move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_TOKN move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_UIWA move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFDF move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFDV move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFGV move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFIO move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFND move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFNP move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFNV move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFRI move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFRV move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFTI move  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_WF_WFTN move  tablespace LINDEX_TS ;
alter TABLE GS_GC.GS_GC_STATS move  tablespace LINDEX_TS ;
alter TABLE GS_GC.QUERYDEFINITIONSTORE move  tablespace LINDEX_TS ;
alter TABLE GS_GC.SESSIONINFO move  tablespace LINDEX_TS ;
alter TABLE GS_GC.TEMP move  tablespace LINDEX_TS ;
alter TABLE GS_GC.TEMP1 move  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_POS1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.SYS_C00129509 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_SEC1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_SEC1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_AUD1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_EQP1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_EQP1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_FIP1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_FIP1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_VRT1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_VRT1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.GS_GC_STATS rebuild  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_ISPS move partition FT_T_ISPS_P0 tablespace LINDEX_TS ;
alter INDEX GS_GC.POS2_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.POS2_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_EV_EVIS_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_EVIS_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_RTG1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_RTG1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.UK_85RGSKT09THD8MKKFL3TB0Y81 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_X_EXTR_TMP001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.SYS_C00121596 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.UK_1DMY087NHBYKUCPGJIPCNYLUV rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.SYS_C00121608 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.SYS_C00121611 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_AUGP_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_FFRL_INST_MNEM rebuild  tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_TRID move subpartition FT_T_TRID_P1_DONE tablespace LINDEX_TS ;
alter TABLE GS_GC.FT_T_TRID move subpartition FT_T_TRID_P1_NEW tablespace LINDEX_TS ;
alter INDEX GS_GC.FT_T_POS1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_GC.SYS_C00129510 rebuild  tablespace LINDEX_TS ;
alter TABLE GS_VD.FT_D_DMID move  tablespace LINDEX_TS ;
alter TABLE GS_VD.FT_T_COMC move  tablespace LINDEX_TS ;
alter TABLE GS_VD.FT_T_SEC1 move  tablespace LINDEX_TS ;
alter TABLE GS_VD.GS_VD_STATS move  tablespace LINDEX_TS ;
alter INDEX GS_VD.FT_T_SEC1_PK rebuild  tablespace LINDEX_TS ;
alter INDEX GS_VD.FT_X_SEC1_U001 rebuild  tablespace LINDEX_TS ;
alter INDEX GS_VD.FT_T_FFRL_INST_MNEM rebuild  tablespace LINDEX_TS ;
alter INDEX GS_VD.GS_VD_STATS rebuild  tablespace LINDEX_TS ;
Elapsed: 00:00:01.47
alter table GS_CDC.FT_T_BNVL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FIID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FINR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FINS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FNCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FPGU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FPRO move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FRAP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISPC move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISSU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MIXR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MKID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MKIS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACCL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_SEC1 move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_POS1 move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_POS2 move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_GUNT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACCV move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNID move tablespace LINDEX_TS;
alter table GS_GC.FT_EV_EVIS move tablespace LINDEX_TS;
alter table GS_VD.FT_EV_EVIS move tablespace LINDEX_TS;
alter table GS_CDC.FT_O_ADEL move tablespace LINDEX_TS;
alter table GS_CDC.FT_O_ADTL move tablespace LINDEX_TS;
alter table GS_CDC.FT_STG_TRNS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_GCCM move tablespace LINDEX_TS;
alter table GS_GC.FT_T_RTG1 move tablespace LINDEX_TS;
alter table GS_VD.FT_T_MSGV move tablespace LINDEX_TS;
alter table GS_VD.FT_T_NTPV move tablespace LINDEX_TS;
alter table GS_GC.FT_T_ISPC move tablespace LINDEX_TS;
alter table GS_GC.FT_D_DMID move tablespace LINDEX_TS;
alter table GS_VD.FT_D_DMID move tablespace LINDEX_TS;
alter table GS_VD.FT_T_ISPC move tablespace LINDEX_TS;
alter table GS_VD.FT_T_POSV move tablespace LINDEX_TS;
alter table GS_GC.ERRORINFO move tablespace LINDEX_TS;
alter table GS_GC.ESCALATION move tablespace LINDEX_TS;
alter table GS_GC.EVENTTYPES move tablespace LINDEX_TS;
alter table GS_GC.NODEINSTANCELOG move tablespace LINDEX_TS;
alter table GS_GC.NOTIFICATION move tablespace LINDEX_TS;
alter table GS_GC.NOTIFICATION_BAS move tablespace LINDEX_TS;
alter table GS_GC.NOTIFICATION_RECIPIENTS move tablespace LINDEX_TS;
alter table GS_GC.NOTIFICATION_EMAIL_HEADER move tablespace LINDEX_TS;
alter table GS_GC.ORGANIZATIONALENTITY move tablespace LINDEX_TS;
alter table GS_GC.PEOPLEASSIGNMENTS_BAS move tablespace LINDEX_TS;
alter table GS_GC.PEOPLEASSIGNMENTS_EXCLOWNERS move tablespace LINDEX_TS;
alter table GS_GC.PEOPLEASSIGNMENTS_POTOWNERS move tablespace LINDEX_TS;
alter table GS_GC.PEOPLEASSIGNMENTS_RECIPIENTS move tablespace LINDEX_TS;
alter table GS_GC.PEOPLEASSIGNMENTS_STAKEHOLDERS move tablespace LINDEX_TS;
alter table GS_GC.PROCESSINSTANCELOG move tablespace LINDEX_TS;
alter table GS_GC.REASSIGNMENT move tablespace LINDEX_TS;
alter table GS_GC.REASSIGNMENT_POTENTIALOWNERS move tablespace LINDEX_TS;
alter table GS_GC.TASK move tablespace LINDEX_TS;
alter table GS_GC.TASKDEF move tablespace LINDEX_TS;
alter table GS_GC.TASKEVENT move tablespace LINDEX_TS;
alter table GS_GC.TASKVARIABLEIMPL move tablespace LINDEX_TS;
alter table GS_GC.VARIABLEINSTANCELOG move tablespace LINDEX_TS;
alter table GS_GC.FT_INTRNL_MDOC move tablespace LINDEX_TS;
alter table GS_GC.FT_INTRNL_MDFL move tablespace LINDEX_TS;
alter table GS_GC.FT_INTRNL_MVRL move tablespace LINDEX_TS;
alter table GS_VD.FT_INTRNL_MDOC move tablespace LINDEX_TS;
alter table GS_VD.FT_INTRNL_MDFL move tablespace LINDEX_TS;
alter table GS_VD.FT_INTRNL_MVRL move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MSRC move tablespace LINDEX_TS;
alter table GS_VD.FT_T_MSRC move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFGV move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFNP move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MSGF move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MSGR move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MSGS move tablespace LINDEX_TS;
alter table GS_VD.FT_T_TRET move tablespace LINDEX_TS;
alter table GS_VD.FT_ERR_ISPC move tablespace LINDEX_TS;
alter table GS_VD.FT_O_VDCP move tablespace LINDEX_TS;
alter table GS_VD.FT_T_COMC move tablespace LINDEX_TS;
alter table GS_GC.FT_BAK_MMTL move tablespace LINDEX_TS;
alter table GS_GC.ATTACHMENT move tablespace LINDEX_TS;
alter table GS_GC.AUDITTASKIMPL move tablespace LINDEX_TS;
alter table GS_GC.BAMTASKSUMMARY move tablespace LINDEX_TS;
alter table GS_GC.CONTEXTMAPPINGINFO move tablespace LINDEX_TS;
alter table GS_GC.CORRELATIONKEYINFO move tablespace LINDEX_TS;
alter table GS_GC.CORRELATIONPROPERTYINFO move tablespace LINDEX_TS;
alter table GS_GC.DEADLINE move tablespace LINDEX_TS;
alter table GS_GC.DELEGATION_DELEGATES move tablespace LINDEX_TS;
alter table GS_VD.FT_T_MSGF move tablespace LINDEX_TS;
alter table GS_VD.FT_T_MSGP move tablespace LINDEX_TS;
alter table GS_VD.FT_T_MSGR move tablespace LINDEX_TS;
alter table GS_VD.FT_T_MSGS move tablespace LINDEX_TS;
alter table GS_GC.BOOLEANEXPRESSION move tablespace LINDEX_TS;
alter table GS_GC.CONTENT move tablespace LINDEX_TS;
alter table GS_GC.DEPLOYMENTSTORE move tablespace LINDEX_TS;
alter table GS_GC.I18NTEXT move tablespace LINDEX_TS;
alter table GS_GC.PROCESSINSTANCEINFO move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_TKTJ move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFDF move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFIO move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFND move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFNV move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFPM move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFTJ move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFTN move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MSGV move tablespace LINDEX_TS;
alter table GS_GC.FT_T_NTPV move tablespace LINDEX_TS;
alter table GS_GC.FT_T_POSV move tablespace LINDEX_TS;
alter table GS_GC.FT_T_TRET move tablespace LINDEX_TS;
alter table GS_GC.FT_ERR_ISPC move tablespace LINDEX_TS;
alter table GS_GC.FT_O_VDCP move tablespace LINDEX_TS;
alter table GS_GC.FT_T_COMC move tablespace LINDEX_TS;
alter table GS_GC.FT_T_POS2 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_POS1 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_SEC1 move tablespace LINDEX_TS;
alter table GS_GC.FT_CFG_PUB1 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_PBC1 move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ABMR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACCT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACCR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACGU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACTA move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AISR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNCL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNPT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNCM move tablespace LINDEX_TS;
alter table GS_GC.FT_T_BKS1 move tablespace LINDEX_TS;
alter table GS_VD.FT_T_POS1 move tablespace LINDEX_TS;
alter table GS_VD.FT_T_POS2 move tablespace LINDEX_TS;
alter table GS_VD.FT_T_RTG1 move tablespace LINDEX_TS;
alter table GS_VD.FT_T_SEC1 move tablespace LINDEX_TS;
alter table GS_GC.TEMP1 move tablespace LINDEX_TS;
alter table GS_GC.TEMP move tablespace LINDEX_TS;
alter table GS_CDC.FT_WF_UIWA move tablespace LINDEX_TS;
alter table GS_GC.QUERYDEFINITIONSTORE move tablespace LINDEX_TS;
alter table GS_GC.REQUESTINFO move tablespace LINDEX_TS;
alter table GS_GC.SESSIONINFO move tablespace LINDEX_TS;
alter table GS_GC.WORKITEMINFO move tablespace LINDEX_TS;
alter table GS_GC.EMAIL_HEADER move tablespace LINDEX_TS;
alter table GS_GC.TASK_COMMENT move tablespace LINDEX_TS;
alter table GS_GC.FT_MV_EXP_TYP move tablespace LINDEX_TS;
alter table GS_GC.FT_MV_TRID_STAT move tablespace LINDEX_TS;
alter table GS_VD.FT_MV_EXP_TYP move tablespace LINDEX_TS;
alter table GS_VD.FT_MV_TRID_STAT move tablespace LINDEX_TS;
alter table GS_GC.FT_T_ISID_20180417 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MKIS_20180417 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MIXR_20180417 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_AUD1 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_FIP1 move tablespace LINDEX_TS;
alter table GS_GC.FT_T_EQP1 move tablespace LINDEX_TS;
alter table GS_GC.FT_CFG_VRT1 move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ETMG move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISAS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FECH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_TTRL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FPTR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AUOR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AOST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AOID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AOPT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNPS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNVC move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISAN move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_TTCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MNPU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_CACR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACGP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACGR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ACTP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ADTP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AICL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AUGP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AUGR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AURP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_AUSR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BDCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BDST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNGU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BNTY move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BOOK move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_CCRF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_CRGP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_CRGR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_CUST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_DSID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_DSRC move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_DWDS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_EADR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_EDMV move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_EIAT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_EIST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ENCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ENTR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ERVL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FFRL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FICL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FIDE move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BALH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_BHST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_EXTR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ETID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ETCL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ETAM move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_EXST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_TRCP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FIGU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FIRT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FLDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FNSC move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FNSR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_FRIP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_GUID move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_IDMV move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_IEDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_IEVP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_INCL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_INCS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_IPDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_IPST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_IRTY move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISAM move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISCD move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISCL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISCM move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISDE move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISGP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISGR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISGU move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISLL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISMC move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISRT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISTA move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ISTY move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_LMCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_LMST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MADR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MRKT move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_MUST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_OPCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_OVRC move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_PEDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_PEVP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_POSR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_PPDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RGCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RIDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RISS move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RIXR move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RTNG move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RTVL move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_SRLE move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_SRPP move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_STDF move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_SWCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_UWCH move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_UWST move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_ETCM move tablespace LINDEX_TS;
alter table GS_CDC.FT_T_RTG1 move tablespace LINDEX_TS;
alter table GS_GC.FT_LOG_LGPD move tablespace LINDEX_TS;
alter table GS_VD.GS_VD_STATS move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFTI move tablespace LINDEX_TS;
alter table GS_GC.GS_GC_STATS move tablespace LINDEX_TS;
alter table GS_GC.FT_LOG_LOGE move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFRI move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFDV move tablespace LINDEX_TS;
alter table GS_GC.FT_T_MSGP move tablespace LINDEX_TS;
alter table GS_GC.FT_LOG_LOGF move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_WFRV move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_UIWA move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_TKTN move tablespace LINDEX_TS;
alter table GS_GC.FT_WF_TOKN move tablespace LINDEX_TS;
alter table GS_GC.FT_LOG_LOGM move tablespace LINDEX_TS;
Elapsed: 00:00:02.91
alter table GS_GC.FT_T_ISPS move partition FT_T_ISPS_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_CAVJ move partition FT_T_CAVJ_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_HOLH move partition FT_T_HOLH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_COVH move partition FT_T_COVH_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_LOTH move partition FT_T_LOTH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_COVJ move partition FT_T_COVJ_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_HOLJ move partition FT_T_HOLJ_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_LOTH move partition FT_T_LOTH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_CAVJ move partition FT_T_CAVJ_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_ACOH move partition FT_T_ACOH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_ACAH move partition FT_T_ACAH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_POSH move partition FT_T_POSH_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_HOLH move partition FT_T_HOLH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_ATDS move partition FT_T_ATDS_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_HOLJ move partition FT_T_HOLJ_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_ATEV move partition FT_T_ATEV_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_POSJ move partition FT_T_POSJ_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_POSH move partition FT_T_POSH_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_COVJ move partition FT_T_COVJ_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_COVH move partition FT_T_COVH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_POSJ move partition FT_T_POSJ_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_ATEV move partition FT_T_ATEV_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_LOTJ move partition FT_T_LOTJ_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_ACAH move partition FT_T_ACAH_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_ATDS move partition FT_T_ATDS_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_ATRN move partition FT_T_ATRN_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_CAVH move partition FT_T_CAVH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_LOTJ move partition FT_T_LOTJ_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_CAVH move partition FT_T_CAVH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_ISPS move partition FT_T_ISPS_P0 tablespace LINDEX_TS;
alter table GS_GC.FT_T_ACOH move partition FT_T_ACOH_P0 tablespace LINDEX_TS;
alter table GS_VD.FT_T_ATRN move partition FT_T_ATRN_P0 tablespace LINDEX_TS;
Elapsed: 00:00:01.08
alter table GS_GC.FT_T_TRID move subpartition FT_T_TRID_P1_DONE tablespace LINDEX_TS;
alter table GS_GC.FT_T_TRID move subpartition FT_T_TRID_P1_NEW tablespace LINDEX_TS;
alter table GS_VD.FT_T_TRID move subpartition FT_T_TRID_P1_NEW tablespace LINDEX_TS;
alter table GS_VD.FT_T_TRID move subpartition FT_T_TRID_P1_DONE tablespace LINDEX_TS;
Elapsed: 00:00:00.12
alter index GS_GC.SYS_IL0000155476C00011$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_EV_EVIS_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_EVIS_U001 rebuild tablespace LINDEX_TS;
alter index GS_VD.SYS_IL0000155528C00011$$ rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_EV_EVIS_PK rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_X_EVIS_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_RTG1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_RTG1_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_EXTR_TMP001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_FFRL_INST_MNEM rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121597 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121598 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121600 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121601 rebuild tablespace LINDEX_TS;
alter index GS_GC.UK_PTAKA5KOST68H7L3WFLV7W6Y8 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121603 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121604 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121606 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121609 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121612 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121613 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121614 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121615 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121616 rebuild tablespace LINDEX_TS;
alter index GS_GC.PK_FT_T_MSRC rebuild tablespace LINDEX_TS;
alter index GS_VD.PK_FT_T_MSRC rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000143998C00010$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000143998C00009$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144006C00029$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144006C00021$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144014C00004$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144017C00006$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144020C00008$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144023C00003$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144026C00003$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144032C00008$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144038C00013$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144041C00010$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144044C00003$$ rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_T_FFRL_INST_MNEM rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_X_VDCP_I001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_BAK_MMTL_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121586 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121587 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121588 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121591 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121592 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121593 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121594 rebuild tablespace LINDEX_TS;
alter index GS_VD.SYS_IL0000144213C00008$$ rebuild tablespace LINDEX_TS;
alter index GS_VD.SYS_IL0000144219C00013$$ rebuild tablespace LINDEX_TS;
alter index GS_VD.SYS_IL0000144222C00010$$ rebuild tablespace LINDEX_TS;
alter index GS_VD.SYS_IL0000144225C00003$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121589 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144385C00002$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121590 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144388C00002$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.UK_85RGSKT09THD8MKKFL3TB0Y81 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121596 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144391C00004$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121599 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144394C00004$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121605 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144397C00005$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_AUGP_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_VDCP_I001 rebuild tablespace LINDEX_TS;
alter index GS_GC.POS2_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.POS2_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_POS1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_POS1_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_SEC1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_SEC1_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00129509 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00129510 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_ISRV_U001 rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_X_ISRV_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_BKS1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_BKS1_U001 rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_T_POS1_PK rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_X_POS1_U001 rebuild tablespace LINDEX_TS;
alter index GS_VD.POS2_U001 rebuild tablespace LINDEX_TS;
alter index GS_VD.POS2_PK rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_T_RTG1_PK rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_X_RTG1_U001 rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_T_SEC1_PK rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_X_SEC1_U001 rebuild tablespace LINDEX_TS;
alter index GS_CDC.SYS_IL0000226544C00029$$ rebuild tablespace LINDEX_TS;
alter index GS_CDC.SYS_IL0000226544C00021$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.UK_1DMY087NHBYKUCPGJIPCNYLUV rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121608 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144400C00002$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144403C00008$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121610 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144403C00009$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144408C00003$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121611 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144411C00007$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121617 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144414C00002$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121618 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000144417C00003$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_C00121619 rebuild tablespace LINDEX_TS;
alter index GS_GC.I_SNAP$_FT_MV_EXP_TYP rebuild tablespace LINDEX_TS;
alter index GS_GC.I_SNAP$_FT_MV_TRID_STAT rebuild tablespace LINDEX_TS;
alter index GS_VD.I_SNAP$_FT_MV_EXP_TYP rebuild tablespace LINDEX_TS;
alter index GS_VD.I_SNAP$_FT_MV_TRID_STAT rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_MAAF_MMTL_PK rebuild tablespace LINDEX_TS;
alter index GS_VD.FT_MAAF_MMTL_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_AUD1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_FIP1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_FIP1_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_EQP1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_EQP1_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_T_VRT1_PK rebuild tablespace LINDEX_TS;
alter index GS_GC.FT_X_VRT1_U001 rebuild tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000206973C00030$$ rebuild tablespace LINDEX_TS;
alter index GS_GC.GS_GC_STATS rebuild tablespace LINDEX_TS;
alter index GS_VD.SYS_IL0000207139C00030$$ rebuild tablespace LINDEX_TS;
alter index GS_VD.GS_VD_STATS rebuild tablespace LINDEX_TS;
alter index GS_CDC.SYS_IL0000209049C00013$$ rebuild tablespace LINDEX_TS;
Elapsed: 00:00:01.66
alter index GS_VD.SYS_IL0000140876C00012$$ rebuild partition SYS_IL_P496 tablespace LINDEX_TS;
alter index GS_GC.SYS_IL0000140870C00012$$ rebuild partition SYS_IL_P494 tablespace LINDEX_TS;
Elapsed: 00:00:00.38
Elapsed: 00:00:00.08
alter table GS_CDC.FT_T_ISCM move lob(LARGE_CMNT_CLOB) store as (tablespace LINDEX_TS);
alter table GS_CDC.FT_WF_UIWA move lob(ADDL_ACTVY_DATA_CLOB) store as (tablespace LINDEX_TS);
alter table GS_CDC.FT_WF_UIWA move lob(PAY_LOAD_CLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.BOOLEANEXPRESSION move lob(EXPRESSION) store as (tablespace LINDEX_TS);
alter table GS_GC.CONTENT move lob(CONTENT) store as (tablespace LINDEX_TS);
alter table GS_GC.DEPLOYMENTSTORE move lob(DEPLOYMENTUNIT) store as (tablespace LINDEX_TS);
alter table GS_GC.EMAIL_HEADER move lob(BODY) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_EV_EVIS move lob(ENTITY_CLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_LOG_LOGE move lob(LOG_MSG_BLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_LOG_LOGE move lob(LOG_STACK_TRACK_CLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_T_MSGF move lob(FMT_MSG_BIN) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_T_MSGP move lob(PROC_MSG_BIN) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_T_MSGR move lob(XML_MSG_CLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_T_MSGS move lob(SUB_MSG_BIN) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_UIWA move lob(ADDL_ACTVY_DATA_CLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_UIWA move lob(PAY_LOAD_CLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_WFDV move lob(LARGE_BINARY_VAL_BLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_WFGV move lob(VARIABLE_DFLT_VAL_BLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_WFNP move lob(LARGE_BINARY_VAL_BLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_WFRV move lob(LARGE_BINARY_VAL_BLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_WF_WFTI move lob(RUNTIME_INFO_BLOB) store as (tablespace LINDEX_TS);
alter table GS_GC.GS_GC_STATS move lob(CL1) store as (tablespace LINDEX_TS);
alter table GS_GC.I18NTEXT move lob(TEXT) store as (tablespace LINDEX_TS);
alter table GS_GC.PROCESSINSTANCEINFO move lob(PROCESSINSTANCEBYTEARRAY) store as (tablespace LINDEX_TS);
alter table GS_GC.QUERYDEFINITIONSTORE move lob(QEXPRESSION) store as (tablespace LINDEX_TS);
alter table GS_GC.REQUESTINFO move lob(REQUESTDATA) store as (tablespace LINDEX_TS);
alter table GS_GC.REQUESTINFO move lob(RESPONSEDATA) store as (tablespace LINDEX_TS);
alter table GS_GC.SESSIONINFO move lob(RULESBYTEARRAY) store as (tablespace LINDEX_TS);
alter table GS_GC.TASK_COMMENT move lob(TEXT) store as (tablespace LINDEX_TS);
alter table GS_GC.WORKITEMINFO move lob(WORKITEMBYTEARRAY) store as (tablespace LINDEX_TS);
alter table GS_VD.FT_EV_EVIS move lob(ENTITY_CLOB) store as (tablespace LINDEX_TS);
alter table GS_VD.FT_T_MSGF move lob(FMT_MSG_BIN) store as (tablespace LINDEX_TS);
alter table GS_VD.FT_T_MSGP move lob(PROC_MSG_BIN) store as (tablespace LINDEX_TS);
alter table GS_VD.FT_T_MSGR move lob(XML_MSG_CLOB) store as (tablespace LINDEX_TS);
alter table GS_VD.FT_T_MSGS move lob(SUB_MSG_BIN) store as (tablespace LINDEX_TS);
alter table GS_VD.GS_VD_STATS move lob(CL1) store as (tablespace LINDEX_TS);
Elapsed: 00:00:01.78
alter table GS_VD.FT_T_ATDS move partition FT_T_ATDS_P0 lob(DATA_AREA_TXT) store as (tablespace LINDEX_TS);
alter table GS_GC.FT_T_ATDS move partition FT_T_ATDS_P0 lob(DATA_AREA_TXT) store as (tablespace LINDEX_TS);
Elapsed: 00:00:00.24
