
delete from FT_BE_BEGC
where  BEGC_OID in ('BNCHSEARCH', 'ACCTSEARCH');

DELETE FT_CFG_SBEX WHERE SBDF_OID IN (SELECT SBDF_OID FROM FT_CFG_SBDF WHERE SUBSCRIPTION_NME = 'EIS_DMP_TO_BRS_EOD_BM_POSITION_FX_SUB');
 
DELETE FT_CFG_SBOF WHERE SBDP_OID IN (SELECT SBDP_OID FROM FT_CFG_SBDP WHERE SBDF_OID IN (SELECT SBDF_OID FROM FT_CFG_SBDF WHERE subscription_nme = 'EIS_DMP_TO_BRS_EOD_BM_POSITION_FX_SUB'));
 
DELETE FT_CFG_BEFL WHERE SBDF_OID IN (SELECT SBDF_OID FROM FT_CFG_SBDF WHERE subscription_nme = 'EIS_DMP_TO_BRS_EOD_BM_POSITION_FX_SUB');
 
DELETE FT_CFG_SBDP WHERE SBDF_OID IN (SELECT SBDF_OID FROM FT_CFG_SBDF WHERE subscription_nme = 'EIS_DMP_TO_BRS_EOD_BM_POSITION_FX_SUB');
 
DELETE FT_CFG_SBDF WHERE subscription_nme = 'EIS_DMP_TO_BRS_EOD_BM_POSITION_FX_SUB';


DELETE FROM ft_t_idmv WHERE intrnl_dmn_val_txt = 'BRS_ORDER';

DELETE from ft_t_edmv
where data_src_id = 'BRS'
and  INTRNL_DMN_VAL_ID = 'hIx.s/5a81';

--DELETE from ft_t_edmv WHERE EXT_DMN_VAL_NME in ('CCRC', 'CLIC', 'ECRC', 'ELIC');
DELETE from ft_t_edmv WHERE EXT_DMN_VAL_NME in ('CCRC', 'CLIC', 'ECRC', 'ELIC');

DELETE from ft_t_edmv WHERE INTRNL_DMN_VAL_ID IN (SELECT INTRNL_DMN_VAL_ID from ft_t_idmv WHERE INTRNL_DMN_VAL_NME in ('CCRC', 'CLIC', 'ECRC', 'ELIC'));

DELETE from ft_t_idmv WHERE INTRNL_DMN_VAL_NME in ('CCRC', 'CLIC', 'ECRC', 'ELIC');

commit;