SELECT   INST_ID
        ,TO_CHAR(VALUE / 100, 'FM9990.999') "AAS ESTIMATE" --centiseconds
FROM     GV$METRIC
WHERE    METRIC_NAME = 'Database Time Per Sec'
AND      GROUP_ID = 2 --SYSTEM METRICS SHORT DURATION
ORDER BY INST_ID
/
