-- this checks for extents which are less than 10%
SELECT   DS.SEGMENT_NAME,
         DS.TABLESPACE_NAME,
         100 * (DS.MAX_EXTENTS - COUNT(DE.SEGMENT_NAME))/DS.MAX_EXTENTS "FREE_PCT"
FROM     DBA_EXTENTS DE, DBA_SEGMENTS DS
WHERE    DS.OWNER='CSPE'
AND      DS.SEGMENT_TYPE = 'TABLE'
AND      DS.OWNER = DE.OWNER
AND      DS.SEGMENT_NAME = DE.SEGMENT_NAME
AND      DS.SEGMENT_TYPE = DE.SEGMENT_TYPE
GROUP BY DS.SEGMENT_NAME,
         DS.TABLESPACE_NAME,
         DS.MAX_EXTENTS
HAVING   100 * (DS.MAX_EXTENTS - COUNT(DE.SEGMENT_NAME))/DS.MAX_EXTENTS < 10