begin
    DBMS_STATS.GATHER_TABLE_STATS(
       OWNNAME    => 'TDB'
      ,TABNAME    => 'COUNTERPARTY_TYPE'
      ,PARTNAME   => ''
      ,METHOD_OPT => 'FOR COLUMN '
      ,CASCADE    => TRUE
      ,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE
      ,GRANULARITY => 'ALL'
    );
END;

begin
    DBMS_STATS.GATHER_TABLE_STATS(
       OWNNAME    => 'TDB'
      ,TABNAME    => 'TRADE'
      ,PARTNAME   => 'TRE_M08B_2011'
      ,METHOD_OPT => 'FOR COLUMNS '
      ,CASCADE    => TRUE
      ,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE
      ,GRANULARITY => 'ALL'
      ,force=> true
    );
END;

begin
    DBMS_STATS.GATHER_TABLE_STATS(
       OWNNAME    => USER
      ,TABNAME    => 'SCM_JOURNAL'
      ,METHOD_OPT => 'FOR ALL COLUMNS SIZE 1'
      ,CASCADE    => TRUE
      ,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE
      ,GRANULARITY => 'ALL'
    );
    DBMS_STATS.GATHER_TABLE_STATS(
       OWNNAME    => USER
      ,TABNAME    => 'TMP_SCM_JOURNAL'
      ,METHOD_OPT => 'FOR ALL COLUMNS SIZE 1'
      ,CASCADE    => TRUE
      ,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE
      ,GRANULARITY => 'ALL'
    );
    DBMS_STATS.GATHER_TABLE_STATS(
       OWNNAME    => USER
      ,TABNAME    => 'TMP_SCM_MAN_JNL'
      ,METHOD_OPT => 'FOR ALL COLUMNS SIZE 1'
      ,CASCADE    => TRUE
      ,ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE
      ,GRANULARITY => 'ALL'
    );    
END;