COL OWNER        FOR A15
COL SEGMENT_NAME FOR A30
COL SEGMENT_TYPE FOR A15
SELECT OWNER, SEGMENT_NAME, SEGMENT_TYPE, BYTES / 1024 / 1024 / 1024 GB
FROM   DBA_SEGMENTS
WHERE  (OWNER, SEGMENT_NAME) IN (SELECT OWNER, TABLE_NAME FROM DBA_TABLES WHERE TABLE_NAME = '&1'
                        UNION ALL
                        SELECT OWNER, TABLE_NAME FROM DBA_INDEXES WHERE TABLE_NAME = '&1'
                        UNION ALL
                        SELECT OWNER, SEGMENT_NAME FROM DBA_LOBS WHERE TABLE_NAME = '&1')
/
