SELECT UC1.CONSTRAINT_NAME, UCC1.TABLE_NAME, UCC1.COLUMN_NAME, UCC2.TABLE_NAME, UCC2.COLUMN_NAME, UCC1.POSITION
FROM   USER_CONSTRAINTS UC1, USER_CONS_COLUMNS UCC1, USER_CONS_COLUMNS UCC2
WHERE  UCC2.OWNER = :OWNER
AND    UCC2.TABLE_NAME = :TABLE_NAME
AND    UCC2.OWNER = UC1.R_OWNER
AND    UCC2.CONSTRAINT_NAME = UC1.R_CONSTRAINT_NAME
AND    UC1.OWNER = UCC1.OWNER
AND    UC1.CONSTRAINT_NAME = UCC1.CONSTRAINT_NAME
AND    UC1.TABLE_NAME = UCC1.TABLE_NAME