SET ECHO OFF
SET HEAD OFF
SET PAGESIZE 0
SET FEEDBACK OFF
SELECT * 
FROM   (SELECT 'awr_report_' || TO_CHAR(BEGIN_INTERVAL_TIME, 'yyyymmddhh24mi') || '.html' REP_NAME
              ,DBID
              ,LAG(SNAP_ID) OVER (ORDER BY BEGIN_INTERVAL_TIME) START_SNAP
              ,SNAP_ID END_SNAP
        FROM   DBA_HIST_SNAPSHOT
        WHERE  DBID = (SELECT DBID FROM V$DATABASE@TDBLNL01)
        ORDER BY BEGIN_INTERVAL_TIME DESC)
WHERE   START_SNAP IS NOT NULL;
/
EXIT
